name: Update Changelog

on: [push]

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update changelog
        run: |
          BEFORE_SHA=${{ github.event.before }}
          CURRENT_SHA=${{ github.sha }}
          if [ "$BEFORE_SHA" = "0000000000000000000000000000000000000000" ]; then
            COMMITS=$(git log --pretty=format:"%h|%s|%an|%ad" --date=short -n 10)
          else
            COMMITS=$(git log --pretty=format:"%h|%s|%an|%ad" --date=short "$BEFORE_SHA..$CURRENT_SHA")
          fi

          FEATURES=""
          FIXES=""
          DOCS=""
          STYLE=""
          REFACTOR=""
          TEST=""
          CHORE=""
          OTHER=""

          while IFS= read -r line; do
            MESSAGE=$(echo "$line" | cut -d'|' -f2)
            AUTHOR=$(echo "$line" | cut -d'|' -f3)
            DATE=$(echo "$line" | cut -d'|' -f4)

            if [[ $MESSAGE =~ ^([a-z]+):[[:space:]]*(.*) ]]; then
              TYPE=${BASH_REMATCH[1]}
              DESC=${BASH_REMATCH[2]}
            else
              TYPE="other"
              DESC="$MESSAGE"
            fi

            BULLET="* $DESC ($AUTHOR, $DATE)"
            case $TYPE in
              feat) FEATURES="$FEATURES$BULLET"$'\n' ;;
              fix) FIXES="$FIXES$BULLET"$'\n' ;;
              docs) DOCS="$DOCS$BULLET"$'\n' ;;
              style) STYLE="$STYLE$BULLET"$'\n' ;;
              refactor) REFACTOR="$REFACTOR$BULLET"$'\n' ;;
              test) TEST="$TEST$BULLET"$'\n' ;;
              chore) CHORE="$CHORE$BULLET"$'\n' ;;
              *) OTHER="$OTHER$BULLET"$'\n' ;;
            esac
          done <<< "$COMMITS"

          # Create the new section with proper line breaks
          NEW_SECTION="## Changes from Push on $(date '+%Y-%m-%d')"$'\n\n'

          if [ -n "$FEATURES" ]; then
            NEW_SECTION="${NEW_SECTION}### Features"$'\n'"$FEATURES"$'\n'
          fi

          if [ -n "$FIXES" ]; then
            NEW_SECTION="${NEW_SECTION}### Fixes"$'\n'"$FIXES"$'\n'
          fi

          if [ -n "$DOCS" ]; then
            NEW_SECTION="${NEW_SECTION}### Documentation"$'\n'"$DOCS"$'\n'
          fi

          if [ -n "$STYLE" ]; then
            NEW_SECTION="${NEW_SECTION}### Style"$'\n'"$STYLE"$'\n'
          fi

          if [ -n "$REFACTOR" ]; then
            NEW_SECTION="${NEW_SECTION}### Refactor"$'\n'"$REFACTOR"$'\n'
          fi

          if [ -n "$TEST" ]; then
            NEW_SECTION="${NEW_SECTION}### Tests"$'\n'"$TEST"$'\n'
          fi

          if [ -n "$CHORE" ]; then
            NEW_SECTION="${NEW_SECTION}### Chore"$'\n'"$CHORE"$'\n'
          fi

          if [ -n "$OTHER" ]; then
            NEW_SECTION="${NEW_SECTION}### Other"$'\n'"$OTHER"$'\n'
          fi

          if [ -f CHANGELOG.md ]; then
            # First, fix the existing CHANGELOG.md if it contains literal \n
            sed -i 's/\\n/\'$'\n''/g' CHANGELOG.md
            
            # Then prepend the new section
            printf "%s\n%s" "$NEW_SECTION" "$(cat CHANGELOG.md)" > temp.md
            mv temp.md CHANGELOG.md
          else
            echo -e "# Project Changelog\n\n$NEW_SECTION" > CHANGELOG.md
          fi
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: update changelog [skip ci]"
          file_pattern: CHANGELOG.md
