name: Update Changelog

on: [push]

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update changelog
        run: |
          BEFORE_SHA=${{ github.event.before }}
          CURRENT_SHA=${{ github.sha }}
          if [ "$BEFORE_SHA" = "0000000000000000000000000000000000000000" ]; then
            COMMITS=$(git log --pretty=format:"%h|%s|%an|%ad" --date=short -n 10)
          else
            COMMITS=$(git log --pretty=format:"%h|%s|%an|%ad" --date=short "$BEFORE_SHA..$CURRENT_SHA")
          fi

          TODAY=$(date '+%Y-%m-%d')
          FEATURES=""
          FIXES=""
          DOCS=""
          STYLE=""
          REFACTOR=""
          TEST=""
          CHORE=""
          OTHER=""

          while IFS= read -r line; do
            MESSAGE=$(echo "$line" | cut -d'|' -f2)
            AUTHOR=$(echo "$line" | cut -d'|' -f3)
            DATE=$(echo "$line" | cut -d'|' -f4)

            if [[ $MESSAGE =~ ^([a-z]+):[[:space:]]*(.*) ]]; then
              TYPE=${BASH_REMATCH[1]}
              DESC=${BASH_REMATCH[2]}
            else
              TYPE="other"
              DESC="$MESSAGE"
            fi

            BULLET="* $DESC ($AUTHOR, $DATE)"
            case $TYPE in
              feat) FEATURES="$FEATURES$BULLET"$'\n' ;;
              fix) FIXES="$FIXES$BULLET"$'\n' ;;
              docs) DOCS="$DOCS$BULLET"$'\n' ;;
              style) STYLE="$STYLE$BULLET"$'\n' ;;
              refactor) REFACTOR="$REFACTOR$BULLET"$'\n' ;;
              test) TEST="$TEST$BULLET"$'\n' ;;
              chore) CHORE="$CHORE$BULLET"$'\n' ;;
              *) OTHER="$OTHER$BULLET"$'\n' ;;
            esac
          done <<< "$COMMITS"

          # Create the new section with proper line breaks
          NEW_SECTION="## Changes from Push on $TODAY"$'\n\n'

          if [ -n "$FEATURES" ]; then
            NEW_SECTION="${NEW_SECTION}### Features"$'\n'"$FEATURES"$'\n'
          fi

          if [ -n "$FIXES" ]; then
            NEW_SECTION="${NEW_SECTION}### Fixes"$'\n'"$FIXES"$'\n'
          fi

          if [ -n "$DOCS" ]; then
            NEW_SECTION="${NEW_SECTION}### Documentation"$'\n'"$DOCS"$'\n'
          fi

          if [ -n "$STYLE" ]; then
            NEW_SECTION="${NEW_SECTION}### Style"$'\n'"$STYLE"$'\n'
          fi

          if [ -n "$REFACTOR" ]; then
            NEW_SECTION="${NEW_SECTION}### Refactor"$'\n'"$REFACTOR"$'\n'
          fi

          if [ -n "$TEST" ]; then
            NEW_SECTION="${NEW_SECTION}### Tests"$'\n'"$TEST"$'\n'
          fi

          if [ -n "$CHORE" ]; then
            NEW_SECTION="${NEW_SECTION}### Chore"$'\n'"$CHORE"$'\n'
          fi

          if [ -n "$OTHER" ]; then
            NEW_SECTION="${NEW_SECTION}### Other"$'\n'"$OTHER"$'\n'
          fi

          if [ -f CHANGELOG.md ]; then
            # First, fix the existing CHANGELOG.md if it contains literal \n
            sed -i 's/\\n/\'$'\n''/g' CHANGELOG.md
            
            # Check if there's already a section for today
            if grep -q "## Changes from Push on $TODAY" CHANGELOG.md; then
              # Extract existing content for today
              TODAY_CONTENT=$(sed -n "/## Changes from Push on $TODAY/,/## Changes from/p" CHANGELOG.md | sed '$d')
              # Remove today's section from the file
              sed -i "/## Changes from Push on $TODAY/,/## Changes from/{ /## Changes from/ !d; /## Changes from/ { /## Changes from Push on $TODAY/d; } }" CHANGELOG.md
              
              # Merge new content with existing content for today
              MERGED_SECTION="## Changes from Push on $TODAY"$'\n\n'
              
              # Extract and merge Features
              if [[ "$TODAY_CONTENT" == *"### Features"* ]] || [ -n "$FEATURES" ]; then
                MERGED_SECTION="${MERGED_SECTION}### Features"$'\n'
                if [[ "$TODAY_CONTENT" == *"### Features"* ]]; then
                  EXISTING_FEATURES=$(echo "$TODAY_CONTENT" | sed -n '/### Features/,/###/p' | sed '/###/d' | sed '/^$/d')
                  MERGED_SECTION="${MERGED_SECTION}${EXISTING_FEATURES}"$'\n'
                fi
                if [ -n "$FEATURES" ]; then
                  MERGED_SECTION="${MERGED_SECTION}${FEATURES}"
                fi
                MERGED_SECTION="${MERGED_SECTION}"$'\n'
              fi
              
              # Extract and merge Fixes
              if [[ "$TODAY_CONTENT" == *"### Fixes"* ]] || [ -n "$FIXES" ]; then
                MERGED_SECTION="${MERGED_SECTION}### Fixes"$'\n'
                if [[ "$TODAY_CONTENT" == *"### Fixes"* ]]; then
                  EXISTING_FIXES=$(echo "$TODAY_CONTENT" | sed -n '/### Fixes/,/###/p' | sed '/###/d' | sed '/^$/d')
                  MERGED_SECTION="${MERGED_SECTION}${EXISTING_FIXES}"$'\n'
                fi
                if [ -n "$FIXES" ]; then
                  MERGED_SECTION="${MERGED_SECTION}${FIXES}"
                fi
                MERGED_SECTION="${MERGED_SECTION}"$'\n'
              fi
              
              # Extract and merge Documentation
              if [[ "$TODAY_CONTENT" == *"### Documentation"* ]] || [ -n "$DOCS" ]; then
                MERGED_SECTION="${MERGED_SECTION}### Documentation"$'\n'
                if [[ "$TODAY_CONTENT" == *"### Documentation"* ]]; then
                  EXISTING_DOCS=$(echo "$TODAY_CONTENT" | sed -n '/### Documentation/,/###/p' | sed '/###/d' | sed '/^$/d')
                  MERGED_SECTION="${MERGED_SECTION}${EXISTING_DOCS}"$'\n'
                fi
                if [ -n "$DOCS" ]; then
                  MERGED_SECTION="${MERGED_SECTION}${DOCS}"
                fi
                MERGED_SECTION="${MERGED_SECTION}"$'\n'
              fi
              
              # Extract and merge Style
              if [[ "$TODAY_CONTENT" == *"### Style"* ]] || [ -n "$STYLE" ]; then
                MERGED_SECTION="${MERGED_SECTION}### Style"$'\n'
                if [[ "$TODAY_CONTENT" == *"### Style"* ]]; then
                  EXISTING_STYLE=$(echo "$TODAY_CONTENT" | sed -n '/### Style/,/###/p' | sed '/###/d' | sed '/^$/d')
                  MERGED_SECTION="${MERGED_SECTION}${EXISTING_STYLE}"$'\n'
                fi
                if [ -n "$STYLE" ]; then
                  MERGED_SECTION="${MERGED_SECTION}${STYLE}"
                fi
                MERGED_SECTION="${MERGED_SECTION}"$'\n'
              fi
              
              # Extract and merge Refactor
              if [[ "$TODAY_CONTENT" == *"### Refactor"* ]] || [ -n "$REFACTOR" ]; then
                MERGED_SECTION="${MERGED_SECTION}### Refactor"$'\n'
                if [[ "$TODAY_CONTENT" == *"### Refactor"* ]]; then
                  EXISTING_REFACTOR=$(echo "$TODAY_CONTENT" | sed -n '/### Refactor/,/###/p' | sed '/###/d' | sed '/^$/d')
                  MERGED_SECTION="${MERGED_SECTION}${EXISTING_REFACTOR}"$'\n'
                fi
                if [ -n "$REFACTOR" ]; then
                  MERGED_SECTION="${MERGED_SECTION}${REFACTOR}"
                fi
                MERGED_SECTION="${MERGED_SECTION}"$'\n'
              fi
              
              # Extract and merge Tests
              if [[ "$TODAY_CONTENT" == *"### Tests"* ]] || [ -n "$TEST" ]; then
                MERGED_SECTION="${MERGED_SECTION}### Tests"$'\n'
                if [[ "$TODAY_CONTENT" == *"### Tests"* ]]; then
                  EXISTING_TEST=$(echo "$TODAY_CONTENT" | sed -n '/### Tests/,/###/p' | sed '/###/d' | sed '/^$/d')
                  MERGED_SECTION="${MERGED_SECTION}${EXISTING_TEST}"$'\n'
                fi
                if [ -n "$TEST" ]; then
                  MERGED_SECTION="${MERGED_SECTION}${TEST}"
                fi
                MERGED_SECTION="${MERGED_SECTION}"$'\n'
              fi
              
              # Extract and merge Chore
              if [[ "$TODAY_CONTENT" == *"### Chore"* ]] || [ -n "$CHORE" ]; then
                MERGED_SECTION="${MERGED_SECTION}### Chore"$'\n'
                if [[ "$TODAY_CONTENT" == *"### Chore"* ]]; then
                  EXISTING_CHORE=$(echo "$TODAY_CONTENT" | sed -n '/### Chore/,/###/p' | sed '/###/d' | sed '/^$/d')
                  MERGED_SECTION="${MERGED_SECTION}${EXISTING_CHORE}"$'\n'
                fi
                if [ -n "$CHORE" ]; then
                  MERGED_SECTION="${MERGED_SECTION}${CHORE}"
                fi
                MERGED_SECTION="${MERGED_SECTION}"$'\n'
              fi
              
              # Extract and merge Other
              if [[ "$TODAY_CONTENT" == *"### Other"* ]] || [ -n "$OTHER" ]; then
                MERGED_SECTION="${MERGED_SECTION}### Other"$'\n'
                if [[ "$TODAY_CONTENT" == *"### Other"* ]]; then
                  EXISTING_OTHER=$(echo "$TODAY_CONTENT" | sed -n '/### Other/,/###/p' | sed '/###/d' | sed '/^$/d')
                  MERGED_SECTION="${MERGED_SECTION}${EXISTING_OTHER}"$'\n'
                fi
                if [ -n "$OTHER" ]; then
                  MERGED_SECTION="${MERGED_SECTION}${OTHER}"
                fi
                MERGED_SECTION="${MERGED_SECTION}"$'\n'
              fi
              
              # Prepend the merged section
              printf "%s\n%s" "$MERGED_SECTION" "$(cat CHANGELOG.md)" > temp.md
              mv temp.md CHANGELOG.md
            else
              # No section for today exists, just prepend the new section
              printf "%s\n%s" "$NEW_SECTION" "$(cat CHANGELOG.md)" > temp.md
              mv temp.md CHANGELOG.md
            fi
          else
            echo -e "# Project Changelog\n\n$NEW_SECTION" > CHANGELOG.md
          fi
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: update changelog [skip ci]"
          file_pattern: CHANGELOG.md
