name: Publish Package to npm

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  release:
    types: [created]

jobs:
  build-and-test:
    # Skip if the commit message contains "update changelog [skip ci]"
    if: "!contains(github.event.head_commit.message, 'update changelog [skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"
      - run: npm ci
      - run: npm run build
      # Add tests if you have them
      # - run: npm test

  publish-npm:
    # Skip if the commit message contains "update changelog [skip ci]"
    if: "!contains(github.event.head_commit.message, 'update changelog [skip ci]')"
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org/"
          scope: "@yoda.digital"
      - run: npm ci
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
